
### health check
GET http://localhost:3000/api/health.json HTTP/1.1

### login / request magic link
POST http://localhost:3000/api/login.json HTTP/1.1
content-type: application/json

{
    "email": "aescofier0@jigsy.com"
}

### register
POST http://localhost:3000/api/register.json HTTP/1.1
content-type: application/json

{
    "email": "koen@koen.nl",
    "name": "VNGLST",
    "junk": "junk"
}

### login with token
GET http://localhost:3000/api/login/8e4f8ae2-9af5-4db0-bc33-ec4d71d2dfe1.json HTTP/1.1

    
